# 数据库配置
db_path: data/graylink.db

# 软链接配置
symlink_base_path: data/media

# 文件模式配置
file_patterns:
  - "*.mp4"   # 视频文件
  - "*.mkv"
  - "*.avi"
  - "*.m4v"
  - "*.srt"   # 字幕文件
  - "*.ass"
  - "*.ssa"

# 排除模式配置
exclude_patterns:
  - "**/BDMV/**"        # 蓝光目录
  - "**/CERTIFICATE/**" # 证书目录
  - "**/@eaDir/**"      # Synology缩略图目录
  - "**/lost+found/**"  # 系统恢复目录

# 挂载点配置
mount_points:
  - "/mnt/gdrive"
  - "/media/gdrive"

# Google Drive配置
gdrive_client_id: "460886178493-iosmlmtfplblq1lreaunqk337s5jdtbn.apps.googleusercontent.com"
gdrive_client_secret: "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"
gdrive_token: {"access_token":"ya29.a0ARW5m772lyjvst5b3qJGM476E9HHNwgArGalw9XPuhGEc40E-JkxvfjeBJkN_eDcIUOG-3suLrYhYIaRZjX-xYhO5kJKM--3NoSFJ9HpJ21JW8Wye1lnU2z7NR6H3CmM-ywS1OkEas8vIQtyoo0HW_Lb3z8tooeIvBiApMDONgaCgYKAcYSARESFQHGX2MiLa_yajboUM7NAwo549u4BA0177","token_type":"Bearer","refresh_token":"1//0ed-RDfT-pyOICgYIARAAGA4SNwF-L9IrkpD4Rg1N50vVjdCcT19ToQf4wjAYWC1zZgN81OtZlHMeFUvuUDWx62HwxIdxdxqibyY","expiry":"2025-01-18T04:24:32.19743-05:00"}
gdrive_team_drive_id: null  # 团队硬盘ID，为null时访问个人硬盘
gdrive_root_folder_id: null  # 根文件夹ID，为null时使用根目录
gdrive_scope: "https://www.googleapis.com/auth/drive.readonly"  # API访问范围

# Emby配置
emby_host: http://localhost:8096
emby_api_key: null  # 需要替换为实际的API密钥

# 监控配置
polling_interval: 300  # 轮询间隔（秒） 